version: '3.8'

services:

  ollama:
    image: ollama/ollama:latest
    container_name: iarvis_ollama
    restart: always
    volumes:
      - ./ollama-data:/root/.ollama  # Guarda los modelos
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MAX_LOADED_MODELS=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - iarvis_network

  n8n:
    image: n8nio/n8n:latest
    container_name: iarvis_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://100.102.164.18:5678/
      # Desactivar analíticas
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n:/home/node/.n8n
    networks:
      - iarvis_network
    depends_on:
      - ollama

  backend:
    build: ./backend  # Construye la imagen usando el Dockerfile
    container_name: iarvis_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Hot-reload
    environment:
      - OLLAMA_URL=http://ollama:11434 # URL interna para que el backend hable con Ollama
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook # URL interna para hablar con n8n
    networks:
      - iarvis_network
    depends_on:
      - n8n
      - ollama

  # --- BASE DE DATOS PARA HISTORIAL DE CHAT ---
  postgres:
    image: postgres:15-alpine
    container_name: iarvis_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=chat_history
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - iarvis_network

  # --- VISOR WEB PARA POSTGRES ---
  pgweb:
    image: sosedoff/pgweb:latest
    container_name: iarvis_pgweb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # Conecta automáticamente usando el nombre del contenedor de postgres y las credenciales
      - DATABASE_URL=postgres://n8n_user:n8n_password@postgres:5432/chat_history?sslmode=disable
    networks:
      - iarvis_network
    depends_on:
      - postgres

  # --- BASE DE DATOS VECTORIAL PARA RAG ---
  qdrant:
    image: qdrant/qdrant:latest
    container_name: iarvis_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant-data:/qdrant/storage
    networks:
      - iarvis_network

networks:
  iarvis_network:
    driver: bridge